# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Create Zip Package for Octopus Deploy
      uses: OctopusDeploy/create-zip-package-action@v3.0.2
      with:
        package_id: 'Phoenix'
        version: '1.0.${{github.run_number}}'
        output_folder: './packaging'
        base_path: '/home/runner/work/phoenix-new/phoenix-new/'
        files: |
          **/*.*
    - name: Push Package to Octopus Deploy
      uses: OctopusDeploy/push-package-action@v3.0.4
      with:
        packages: './packaging/Phoenix.1.0.${{github.run_number}}.zip'
        api_key: ${{ secrets.OCTOPUS_APIKEY }}
        server: ${{ secrets.OCTOPUS_SERVER }}
        space: 'Octopus Training'
    - name: Create Octopus release
      uses: OctopusDeploy/create-release-action@v3
      with:
        api_key: ${{ secrets.OCTOPUS_APIKEY }}
        server: ${{ secrets.OCTOPUS_SERVER }}
        project: 'Phoenix'
