# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: PHP ZIP 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Create Zip Package for Octopus Deploy
    uses: OctopusDeploy/create-zip-package-action@v3.0.0
    with:
      package_id: 'phoenix'
      version: '1.0.${{github.run_number}}'
      output_folder: './packaging'
      base_path: /home/runner/work/phoenix-new
      files: 
        **/*.*
    - name: Push a package to Octopus Deploy
    uses: OctopusDeploy/push-package-action@v3
    env:
      OCTOPUS_URL: ${{ secrets.SERVER }}
      OCTOPUS_API_KEY: ${{ secrets.API_KEY }}
      OCTOPUS_SPACE: 'Default'
    with:
      packages: 
        ./packaging/phoenix.1.0.${{github.run_number}}.zip
